# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPyT0SEFprJcFBVh9hKj4FvDGsB0cmu6
"""

import pandas as pd
import numpy as np

from dash import Dash, dcc, html
import plotly.express as px
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression

# =========================
# 1) Leitura do dataset
# =========================
ARQUIVO = "ecommerce_estatistica.csv"
df = pd.read_csv(ARQUIVO)

# Garantir colunas esperadas (ajusta se o seu CSV tiver nomes diferentes)
# Aqui eu uso os nomes que apareceram no módulo anterior:
COL_PRECO = "Preço"
COL_QTD = "Qtd_Vendidos_Cod"
COL_MARCA = "Marca"
COL_GENERO = "Gênero"

# Colunas numéricas para correlação
num_df = df.select_dtypes(include=[np.number])

# =========================
# 2) Gráficos (Plotly)
# =========================

# 2.1 Histograma (Preço)
fig_hist = px.histogram(
    df.dropna(subset=[COL_PRECO]),
    x=COL_PRECO,
    nbins=30,
    title="Distribuição de Preços (Histograma)"
)
fig_hist.update_layout(xaxis_title="Preço", yaxis_title="Quantidade de produtos")

# 2.2 Dispersão (Preço x Qtd)
df_disp = df.dropna(subset=[COL_PRECO, COL_QTD])
fig_scatter = px.scatter(
    df_disp,
    x=COL_PRECO,
    y=COL_QTD,
    title="Preço vs Quantidade Vendida (Dispersão)",
)
fig_scatter.update_layout(xaxis_title="Preço", yaxis_title="Qtd_Vendidos_Cod")

# 2.3 Mapa de calor (Correlação)
corr = num_df.corr(numeric_only=True)
fig_heat = px.imshow(
    corr,
    text_auto=True,
    title="Mapa de Calor — Correlação (variáveis numéricas)"
)
fig_heat.update_layout(xaxis_title="Variáveis", yaxis_title="Variáveis")

# 2.4 Barra (Top 10 marcas por volume vendido)
top_marcas = (
    df.groupby(COL_MARCA, dropna=False)[COL_QTD]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)
top_marcas[COL_MARCA] = top_marcas[COL_MARCA].fillna("Não informado")

fig_bar = px.bar(
    top_marcas,
    x=COL_MARCA,
    y=COL_QTD,
    title="Top 10 Marcas por Volume Vendido (Barra)"
)
fig_bar.update_layout(xaxis_title="Marca", yaxis_title="Soma de Qtd_Vendidos_Cod")

# 2.5 Pizza (Distribuição por Gênero)
genero_counts = df[COL_GENERO].fillna("Não informado").value_counts().reset_index()
genero_counts.columns = [COL_GENERO, "qtd"]

# Se tiver muitas categorias, mantém top 6 e agrupa resto
TOP_N = 6
if len(genero_counts) > TOP_N:
    top = genero_counts.head(TOP_N).copy()
    outros = genero_counts.iloc[TOP_N:]["qtd"].sum()
    top.loc[len(top)] = ["Outros", outros]
    genero_counts = top

fig_pie = px.pie(
    genero_counts,
    names=COL_GENERO,
    values="qtd",
    title="Distribuição de Produtos por Gênero (Pizza)"
)

# 2.6 Densidade (KDE) do Preço
# Plotly não tem KDE “nativo” igual pandas, mas dá pra simular usando density_contour 1D via histogram normalizado
# Para manter simples e didático, uso histograma normalizado com curva suave (estimativa simples)
preco = df[COL_PRECO].dropna().values
hist_y, hist_x = np.histogram(preco, bins=40, density=True)
centros = (hist_x[:-1] + hist_x[1:]) / 2

fig_density = go.Figure()
fig_density.add_trace(go.Scatter(x=centros, y=hist_y, mode="lines", name="Densidade"))
fig_density.update_layout(
    title="Densidade de Preços (aproximação)",
    xaxis_title="Preço",
    yaxis_title="Densidade"
)

# 2.7 Regressão (Preço -> Qtd_Vendidos_Cod)
df_reg = df.dropna(subset=[COL_PRECO, COL_QTD]).copy()

X = df_reg[[COL_PRECO]].values
y = df_reg[COL_QTD].values

modelo = LinearRegression()
modelo.fit(X, y)

x_line = np.linspace(X.min(), X.max(), 200).reshape(-1, 1)
y_line = modelo.predict(x_line)

fig_reg = go.Figure()
fig_reg.add_trace(go.Scatter(x=df_reg[COL_PRECO], y=df_reg[COL_QTD], mode="markers", name="Pontos"))
fig_reg.add_trace(go.Scatter(x=x_line.flatten(), y=y_line, mode="lines", name="Linha de Regressão"))
fig_reg.update_layout(
    title="Regressão Linear: Preço vs Qtd_Vendidos_Cod",
    xaxis_title="Preço",
    yaxis_title="Qtd_Vendidos_Cod"
)

# =========================
# 3) App Dash
# =========================
app = Dash(__name__)
app.title = "Dashboard E-commerce"

app.layout = html.Div(
    style={"maxWidth": "1100px", "margin": "0 auto", "padding": "16px"},
    children=[
        html.H1("Dashboard E-commerce — Visualização e Insights"),

        html.Div(
            style={"marginBottom": "12px"},
            children=[
                html.P(
                    "Este dashboard exibe as visualizações do módulo anterior para facilitar o consumo pelo cliente final."
                ),
            ],
        ),

        dcc.Tabs(
            children=[
                dcc.Tab(label="Histograma", children=[dcc.Graph(figure=fig_hist)]),
                dcc.Tab(label="Dispersão", children=[dcc.Graph(figure=fig_scatter)]),
                dcc.Tab(label="Mapa de Calor", children=[dcc.Graph(figure=fig_heat)]),
                dcc.Tab(label="Barras", children=[dcc.Graph(figure=fig_bar)]),
                dcc.Tab(label="Pizza", children=[dcc.Graph(figure=fig_pie)]),
                dcc.Tab(label="Densidade", children=[dcc.Graph(figure=fig_density)]),
                dcc.Tab(label="Regressão", children=[dcc.Graph(figure=fig_reg)]),
            ]
        ),

        html.Hr(),
        html.Small("Feito com Dash + Plotly | Dataset: ecommerce_estatistica.csv"),
    ]
)

if __name__ == "__main__":
    app.run_server(debug=True)